### ISSUE TITLE
iOS10下  好像播放不了

### ISSUE THREAD

**Issue by Yongle-Fu** [ZhongshanHuang/VideoPlayer#1]

**Comment by ZhongshanHuang** [comment]
有报什么错误吗？暂时在老家网速太慢，没办法下载一个10.0的模拟器

**Comment by ablettchen** [comment]
iOS  10 报错

{
    NSLocalizedDescription = "Cannot Open";
    NSLocalizedFailureReason = "This media may be damaged.";
    NSUnderlyingError = "Error Domain=NSOSStatusErrorDomain Code=-12848 \"(null)\"";
}
