### ISSUE TITLE
iOS 10 不能播放

### ISSUE THREAD

**Issue by ablettchen** [ZhongshanHuang/VideoPlayer#3]
{
    NSLocalizedDescription = "Cannot Open";
    NSLocalizedFailureReason = "This media may be damaged.";
    NSUnderlyingError = "Error Domain=NSOSStatusErrorDomain Code=-12848 \"(null)\"";
}

**Comment by ZhongshanHuang** [comment]
我下载了iOS 10 的模拟器，发现在iOS 10 发起的请求header不一样，里面包含了If-None-Match和If-Modified-Since，导致请求返回的数据有出入，请将将请求的缓存策略改为.reloadIgnoringLocalCacheData，如下所示（问题应该是ios10 默认的缓存策略行为不一致导致的）
func remoteDataTask(with url: URL, requestRange: NSRange) -> PoAVPlayerResourceRequestRemoteTask {
        var urlRequest = URLRequest(url: url)
        urlRequest.httpShouldUsePipelining = true
        urlRequest.cachePolicy = .reloadIgnoringLocalCacheData
        let rangeStr = correctRange(requestRange)
        urlRequest.setValue(rangeStr, forHTTPHeaderField: "Range")
        let dataTask = session.dataTask(with: urlRequest)
        let remoteTask = PoAVPlayerResourceRequestRemoteTask(task: dataTask, requestRange: requestRange)
        tasks[dataTask] = remoteTask
        return remoteTask
    }

**Comment by ablettchen** [comment]
感谢！
